[package]
name = "repository"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1.0"
chrono = "0.4"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
futures = "0.3"
lapin = "2"
redis = { version = "0.24", features = ["tokio-comp", "streams"] }
git2 = "0.18"
regex = "1"
argon2 = "0.5"
jsonwebtoken = "9"
uuid = { version = "1.8", features = ["serde", "v4"] }
base64 = "0.22"
json5 = "0.4"
tracing = "0.1"
aes-gcm = "0.10"
sha2 = "0.10"
bip39 = "2.0"
rand = "0.8"
hex = "0.4"